### ISSUE TITLE
Python Tests Fail

### ISSUE THREAD

**Issue by ngmor** [omnid/cmakeme#5]
After building this package with `colcon build` and running colcon test, the test fails with the message:
```
- cmakeme_test
  <<< failure message
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/ngm/classes/final/compile/build/cmakeme/tests
    [100%] Updating cmakeme_tests_git_hash.h
    [100%] Built target git_hash
    /usr/bin/python3.10: No module named build
    gmake[2]: *** [CMakeFiles/cmakeme_python_test-python.dir/build.make:71: CMakeFiles/cmakeme_python_test-python] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/cmakeme_python_test-python.dir/all] Error 2
    gmake: *** [Makefile:136: all] Error 2
    CMake Error at /home/ngm/classes/final/compile/src/cmakeme/tests/run_tests.cmake:10 (message):
      Could not find
      /home/ngm/classes/final/compile/build/cmakeme/tests/dist/cmakeme_python_test-0.0.1-py3-none-any.whl
  >>>
```

This failure is bypassed by running `sudo apt install python3-build`. We might need a dependency on this.

After installing this Python module, the test still fails with the following error message:

```
- cmakeme_test
  <<< failure message
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/ngm/classes/final/compile/build/cmakeme/tests
    [100%] Updating cmakeme_tests_git_hash.h
    [100%] Built target git_hash
    * Creating venv isolated environment...
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/build/__main__.py", line 372, in main
        built = build_call(
      File "/usr/lib/python3/dist-packages/build/__main__.py", line 229, in build_package_via_sdist
        sdist = _build(isolation, builder, outdir, 'sdist', config_settings, skip_dependency_check)
      File "/usr/lib/python3/dist-packages/build/__main__.py", line 140, in _build
        return _build_in_isolated_env(builder, outdir, distribution, config_settings)
      File "/usr/lib/python3/dist-packages/build/__main__.py", line 104, in _build_in_isolated_env
        with _IsolatedEnvBuilder() as env:
      File "/usr/lib/python3/dist-packages/build/env.py", line 104, in __enter__
        executable, scripts_dir = _create_isolated_env_venv(self._path)
      File "/usr/lib/python3/dist-packages/build/env.py", line 258, in _create_isolated_env_venv
        executable, script_dir, purelib = _find_executable_and_scripts(path)
      File "/usr/lib/python3/dist-packages/build/env.py", line 303, in _find_executable_and_scripts
        raise RuntimeError(f'Virtual environment creation failed, executable {executable} missing')
    RuntimeError: Virtual environment creation failed, executable /tmp/build-env-81mzpikk/local/bin/python missing
    
    ERROR Virtual environment creation failed, executable /tmp/build-env-81mzpikk/local/bin/python missing
    gmake[2]: *** [CMakeFiles/cmakeme_python_test-python.dir/build.make:71: CMakeFiles/cmakeme_python_test-python] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/cmakeme_python_test-python.dir/all] Error 2
    gmake: *** [Makefile:136: all] Error 2
    CMake Error at /home/ngm/classes/final/compile/src/cmakeme/tests/run_tests.cmake:10 (message):
      Could not find
      /home/ngm/classes/final/compile/build/cmakeme/tests/dist/cmakeme_python_test-0.0.1-py3-none-any.whl
  >>>

```

**Comment by ngmor** [comment]
Changing `enable_testing` to `include(CTest)` in `CMakeLists.txt` changes the output, but ultimately seems to have no effect:
```
- cmakeme_test
  <<< failure message
    -- The C compiler identification is GNU 11.3.0
    -- The CXX compiler identification is GNU 11.3.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found Git: /usr/bin/git (found version "2.34.1") 
    -- CMAKE_BUILD_TYPE="": Defaulting to Debug
    -- Found Python3: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/ngm/classes/final/compile/build/cmakeme/tests
    [100%] Updating cmakeme_tests_git_hash.h
    [100%] Built target git_hash
    * Creating venv isolated environment...
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/build/__main__.py", line 372, in main
        built = build_call(
      File "/usr/lib/python3/dist-packages/build/__main__.py", line 229, in build_package_via_sdist
        sdist = _build(isolation, builder, outdir, 'sdist', config_settings, skip_dependency_check)
      File "/usr/lib/python3/dist-packages/build/__main__.py", line 140, in _build
        return _build_in_isolated_env(builder, outdir, distribution, config_settings)
      File "/usr/lib/python3/dist-packages/build/__main__.py", line 104, in _build_in_isolated_env
        with _IsolatedEnvBuilder() as env:
      File "/usr/lib/python3/dist-packages/build/env.py", line 104, in __enter__
        executable, scripts_dir = _create_isolated_env_venv(self._path)
      File "/usr/lib/python3/dist-packages/build/env.py", line 258, in _create_isolated_env_venv
        executable, script_dir, purelib = _find_executable_and_scripts(path)
      File "/usr/lib/python3/dist-packages/build/env.py", line 303, in _find_executable_and_scripts
        raise RuntimeError(f'Virtual environment creation failed, executable {executable} missing')
    RuntimeError: Virtual environment creation failed, executable /tmp/build-env-ihhxv7pv/local/bin/python missing
    
    ERROR Virtual environment creation failed, executable /tmp/build-env-ihhxv7pv/local/bin/python missing
    gmake[2]: *** [CMakeFiles/cmakeme_python_test-python.dir/build.make:71: CMakeFiles/cmakeme_python_test-python] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/cmakeme_python_test-python.dir/all] Error 2
    gmake: *** [Makefile:136: all] Error 2
    CMake Error at /home/ngm/classes/final/compile/src/cmakeme/tests/run_tests.cmake:10 (message):
      Could not find
      /home/ngm/classes/final/compile/build/cmakeme/tests/dist/cmakeme_python_test-0.0.1-py3-none-any.whl
  >>>
```

**Comment by m-elwin** [comment]
Submitted a pull request to rosdep to add python3-build as a rodsdep. Added the dependency.

**Comment by m-elwin** [comment]
python3 build is now in rosdep due to https://github.com/ros/rosdistro/pull/39236
